val:
  channels:
    - name: depth
      start: 0
      end: 1
      scale:
        min: 0
        max: 131.0
      retype: f4
train:
  channels:
    - name: depth
      start: 0
      end: 1
      scale:
        min: 0
        max: 131.0
      retype: f4