train:
  folder: /mnt/lustre/data/intensity/train
  name: intensity
  ext: .npy
  shuffle: True
  keep_ram: True
val:
  folder: /mnt/lustre/data/intensity/val
  name: intensity_val
  ext: .npy
  shuffle: False
  keep_ram: True
train_loader:
  batch_size: 4
  shuffle: True
  num_workers: 4
  pin_memory: True
val_loader:
  batch_size: 1
  shuffle: False
  num_workers: 4
  pin_memory: True
  